---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - if ! [ "$PUPPET_GEM_VERSION" = "~> 3" -o "$PUPPET_GEM_VERSION" = "~> 4" ]; then gem update --system; fi
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"

notifications:
  email: false
