name    'ghoneycutt-rsyslog'
version '0.2.0'
source 'git://github.com/ghoneycutt/puppet-module-rsyslog.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage rsyslog'
description 'Manage rsyslog'
project_page 'https://github.com/ghoneycutt/puppet-module-rsyslog'

dependency 'ghoneycutt/sysklogd', '1.x'
dependency 'ghoneycutt/common', '1.x'
