name    'ghoneycutt-rsyslog'
version '0.13.0'
source 'git://github.com/ghoneycutt/puppet-module-rsyslog.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage rsyslog'
description 'Manage rsyslog'
project_page 'https://github.com/ghoneycutt/puppet-module-rsyslog'

dependency 'ghoneycutt/sysklogd', '>= 1.0.0'
dependency 'ghoneycutt/common',   '>= 1.0.0'
dependency 'puppetlabs/stdlib',   '>= 3.2.0'
