name    'ghoneycutt-rsyslog'
version '0.1.0'
source 'git://github.com/ghoneycutt/puppet-module-rsyslog.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage rsyslog'
description 'Manage rsyslog'
project_page 'https://github.com/ghoneycutt/puppet-module-rsyslog'

dependency 'ghoneycutt/sysklogd, '>= 0.0.1'
dependency 'ghoneycutt/common, '>= 0.0.1'
